// resources/react/components/fields/KeyValue.tsx
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';
import { useLocalization } from '@laravilt/support/composables/useLocalization';
import { resolveIcon } from '@laravilt/support/lib/icons';
import { GripVertical, Plus, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';

interface KeyValuePair {
    key: string;
    value: string;
}

type KeyValueModel = Record<string, string> | KeyValuePair[];

export interface KeyValueProps {
    name?: string;
    value?: KeyValueModel;
    modelValue?: KeyValueModel;
    label?: string;
    helperText?: string;
    required?: boolean;
    keyLabel?: string;
    valueLabel?: string;
    addButtonLabel?: string;
    reorderable?: boolean;
    deletable?: boolean;
    prefixIcon?: string;
    suffixIcon?: string;
    prefixIconColor?: string;
    suffixIconColor?: string;
    onUpdateModelValue?: (value: KeyValueModel) => void;
    onUpdateValue?: (value: KeyValueModel) => void;
    [key: string]: any;
}

const EMPTY_MODEL: Record<string, string> = {};

// Convert the model to array format for easier manipulation
const toPairs = (model: KeyValueModel | null | undefined): KeyValuePair[] =>
    Array.isArray(model) ? model : Object.entries(model || {}).map(([key, value]) => ({ key, value }));

// Helper to get Tailwind color classes for icons
const getIconColorClass = (color?: string) => {
    if (!color) return 'text-muted-foreground';

    // Map common color names to Tailwind classes
    const colorMap: Record<string, string> = {
        primary: 'text-primary',
        secondary: 'text-secondary',
        success: 'text-green-600',
        danger: 'text-red-600',
        warning: 'text-yellow-600',
        info: 'text-blue-600',
        muted: 'text-muted-foreground',
        destructive: 'text-destructive',
    };

    return colorMap[color] || `text-${color}`;
};

export default function KeyValue({
    name,
    modelValue = EMPTY_MODEL,
    label,
    helperText,
    required,
    keyLabel = 'Key',
    valueLabel = 'Value',
    addButtonLabel = 'Add Item',
    reorderable = false,
    deletable = true,
    prefixIcon,
    suffixIcon,
    prefixIconColor,
    suffixIconColor,
    onUpdateModelValue,
    onUpdateValue,
}: KeyValueProps) {
    // Initialize localization
    const { trans } = useLocalization();

    // Translated labels
    const translatedKeyLabel = keyLabel !== 'Key' ? keyLabel : trans('key_value.key_label');
    const translatedValueLabel = valueLabel !== 'Value' ? valueLabel : trans('key_value.value_label');
    const translatedAddButtonLabel = addButtonLabel !== 'Add Item' ? addButtonLabel : trans('key_value.add_button_label');

    const [pairs, setPairs] = useState<KeyValuePair[]>(() => toPairs(modelValue));

    // Re-sync on external changes (reset, reactive update). Our own emits echo back unchanged and are
    // skipped, so in-progress rows (e.g. one with an empty key) are not dropped.
    const lastEmitted = useRef<KeyValueModel>(modelValue);
    useEffect(() => {
        if (modelValue === lastEmitted.current) return;
        lastEmitted.current = modelValue;
        setPairs(toPairs(modelValue));
    }, [modelValue]);

    // Emit as object if original was object, array otherwise
    const normalize = (nextPairs: KeyValuePair[]): KeyValueModel => {
        if (Array.isArray(modelValue)) {
            return nextPairs;
        }
        const obj: Record<string, string> = {};
        nextPairs.forEach((pair) => {
            if (pair.key) {
                obj[pair.key] = pair.value;
            }
        });
        return obj;
    };

    const emitUpdate = (nextPairs: KeyValuePair[]) => {
        const next = normalize(nextPairs);
        lastEmitted.current = next;
        onUpdateModelValue?.(next);
        onUpdateValue?.(next);
    };

    const addPair = () => {
        const next = [...pairs, { key: '', value: '' }];
        setPairs(next);
        emitUpdate(next);
    };

    const removePair = (index: number) => {
        const next = [...pairs];
        next.splice(index, 1);
        setPairs(next);
        emitUpdate(next);
    };

    const updatePair = (index: number, field: 'key' | 'value', value: string) => {
        const next = pairs.map((pair, i) => (i === index ? { ...pair, [field]: value } : pair));
        setPairs(next);
        emitUpdate(next);
    };

    const PrefixIcon = resolveIcon(prefixIcon);
    const SuffixIcon = resolveIcon(suffixIcon);

    return (
        <div className="w-full space-y-3">
            {/* Label */}
            {label && (
                <label htmlFor={name} className="text-sm font-medium block text-foreground">
                    {label}
                    {required && <span className="text-destructive ms-0.5">*</span>}
                </label>
            )}

            {/* Hidden input for form submission */}
            {name && <input type="hidden" name={name} value={JSON.stringify(normalize(pairs))} />}

            {/* Header with icons */}
            {(PrefixIcon || suffixIcon) && (
                <div className="flex items-center justify-between">
                    {PrefixIcon && <PrefixIcon className={cn('h-4 w-4', getIconColorClass(prefixIconColor))} />}
                    {SuffixIcon && <SuffixIcon className={cn('h-4 w-4', getIconColorClass(suffixIconColor))} />}
                </div>
            )}

            {/* Pairs list */}
            <div className="space-y-2">
                {pairs.map((pair, index) => (
                    <div key={index} className="flex items-center gap-2">
                        {/* Drag handle (if reorderable) */}
                        {reorderable && (
                            <button type="button" className="cursor-grab hover:text-primary shrink-0">
                                <GripVertical className="h-4 w-4" />
                            </button>
                        )}

                        {/* Key input */}
                        <Input
                            value={pair.key}
                            placeholder={translatedKeyLabel}
                            className="flex-1"
                            onChange={(e) => updatePair(index, 'key', e.target.value)}
                        />

                        {/* Value input */}
                        <Input
                            value={pair.value}
                            placeholder={translatedValueLabel}
                            className="flex-1"
                            onChange={(e) => updatePair(index, 'value', e.target.value)}
                        />

                        {/* Delete button */}
                        {deletable && (
                            <Button
                                type="button"
                                variant="ghost"
                                size="sm"
                                className="shrink-0 h-9 w-9 p-0"
                                onClick={() => removePair(index)}
                            >
                                <X className="h-4 w-4" />
                            </Button>
                        )}
                    </div>
                ))}
            </div>

            {/* Add button */}
            <Button type="button" variant="outline" size="sm" className="w-full" onClick={addPair}>
                <Plus className="h-4 w-4 mr-2" />
                {translatedAddButtonLabel}
            </Button>

            {/* Helper text */}
            {helperText && <p className="text-xs text-muted-foreground mt-1">{helperText}</p>}
        </div>
    );
}

// resources/js/components/fields/KeyValue.vue
<script setup lang="ts">
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import * as LucideIcons from 'lucide-vue-next'
import { Plus, X, GripVertical } from 'lucide-vue-next'
import { ref, computed, watch } from 'vue'
import { useLocalization } from '@laravilt/support/composables'

// Initialize localization
const { trans } = useLocalization()

interface KeyValuePair {
  key: string
  value: string
}

interface Props {
  name?: string
  value?: Record<string, string> | KeyValuePair[]
  modelValue?: Record<string, string> | KeyValuePair[]
  label?: string
  helperText?: string
  required?: boolean
  keyLabel?: string
  valueLabel?: string
  addButtonLabel?: string
  reorderable?: boolean
  deletable?: boolean
  prefixIcon?: string
  suffixIcon?: string
  prefixIconColor?: string
  suffixIconColor?: string
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: () => ({}),
  keyLabel: 'Key',
  valueLabel: 'Value',
  addButtonLabel: 'Add Item',
  reorderable: false,
  deletable: true,
})

const emit = defineEmits<{
  'update:modelValue': [value: Record<string, string> | KeyValuePair[]]
  'update:value': [value: Record<string, string> | KeyValuePair[]]
}>()

// Computed translated labels
const translatedKeyLabel = computed(() => props.keyLabel !== 'Key' ? props.keyLabel : trans('key_value.key_label'))
const translatedValueLabel = computed(() => props.valueLabel !== 'Value' ? props.valueLabel : trans('key_value.value_label'))
const translatedAddButtonLabel = computed(() => props.addButtonLabel !== 'Add Item' ? props.addButtonLabel : trans('key_value.add_button_label'))

// Helper to get Lucide icon component by name
const getIconComponent = (iconName?: string) => {
  if (!iconName) return null
  // Convert kebab-case or lowercase to PascalCase for Lucide icons
  const pascalCase = iconName
    .split(/[-_\s]/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
  return (LucideIcons as any)[pascalCase] || null
}

// Helper to get Tailwind color classes for icons
const getIconColorClass = (color?: string) => {
  if (!color) return 'text-muted-foreground'

  // Map common color names to Tailwind classes
  const colorMap: Record<string, string> = {
    'primary': 'text-primary',
    'secondary': 'text-secondary',
    'success': 'text-green-600',
    'danger': 'text-red-600',
    'warning': 'text-yellow-600',
    'info': 'text-blue-600',
    'muted': 'text-muted-foreground',
    'destructive': 'text-destructive',
  }

  return colorMap[color] || 'text-muted-foreground'
}

type KeyValueModel = Record<string, string> | KeyValuePair[]

// Convert the model to array format for easier manipulation
const toPairs = (model: KeyValueModel | null | undefined): KeyValuePair[] =>
  Array.isArray(model)
    ? model.map(pair => ({ ...pair }))
    : Object.entries(model || {}).map(([key, value]) => ({ key, value }))

const pairs = ref<KeyValuePair[]>(toPairs(props.modelValue))

// Re-sync on external changes (reset, reactive update). Our own emits echo back unchanged and are
// skipped, so in-progress rows (e.g. one with an empty key) are not dropped.
let lastEmitted: KeyValueModel | undefined = props.modelValue
watch(() => props.modelValue, (model) => {
  if (model === lastEmitted) return
  lastEmitted = model
  pairs.value = toPairs(model)
})

// Emit as object if original was object, array otherwise
const normalize = (nextPairs: KeyValuePair[]): KeyValueModel => {
  if (Array.isArray(props.modelValue)) {
    return nextPairs.map(pair => ({ ...pair }))
  }
  const obj: Record<string, string> = {}
  nextPairs.forEach(pair => {
    if (pair.key) {
      obj[pair.key] = pair.value
    }
  })
  return obj
}

const hiddenValue = computed(() => JSON.stringify(normalize(pairs.value)))

const addPair = () => {
  pairs.value.push({ key: '', value: '' })
  emitUpdate()
}

const removePair = (index: number) => {
  pairs.value.splice(index, 1)
  emitUpdate()
}

const updatePair = (index: number, field: 'key' | 'value', value: string) => {
  pairs.value[index][field] = value
  emitUpdate()
}

const emitUpdate = () => {
  const next = normalize(pairs.value)
  lastEmitted = next
  emit('update:modelValue', next)
  emit('update:value', next)
}
</script>

<template>
  <div class="w-full space-y-3">
    <!-- Label -->
    <label
      v-if="label"
      :for="name"
      class="text-sm font-medium block text-foreground"
    >
      {{ label }}
      <span v-if="required" class="text-destructive ms-0.5">*</span>
    </label>

    <!-- Hidden input for form submission -->
    <input
      v-if="name"
      type="hidden"
      :name="name"
      :value="hiddenValue"
    />

    <!-- Header with icons -->
    <div v-if="getIconComponent(props.prefixIcon) || props.suffixIcon" class="flex items-center justify-between">
      <component
        v-if="getIconComponent(props.prefixIcon)"
        :is="getIconComponent(props.prefixIcon)"
        class="h-4 w-4"
        :class="getIconColorClass(props.prefixIconColor)"
      />
      <component
        v-if="getIconComponent(props.suffixIcon)"
        :is="getIconComponent(props.suffixIcon)"
        class="h-4 w-4"
        :class="getIconColorClass(props.suffixIconColor)"
      />
    </div>

    <!-- Pairs list -->
    <div class="space-y-2">
      <div
        v-for="(pair, index) in pairs"
        :key="index"
        class="flex items-center gap-2"
      >
        <!-- Drag handle (if reorderable) -->
        <button
          v-if="reorderable"
          type="button"
          class="cursor-grab hover:text-primary shrink-0"
        >
          <GripVertical class="h-4 w-4" />
        </button>

        <!-- Key input -->
        <Input
          :model-value="pair.key"
          :placeholder="translatedKeyLabel"
          class="flex-1"
          @input="(e) => updatePair(index, 'key', (e.target as HTMLInputElement).value)"
        />

        <!-- Value input -->
        <Input
          :model-value="pair.value"
          :placeholder="translatedValueLabel"
          class="flex-1"
          @input="(e) => updatePair(index, 'value', (e.target as HTMLInputElement).value)"
        />

        <!-- Delete button -->
        <Button
          v-if="deletable"
          type="button"
          variant="ghost"
          size="sm"
          class="shrink-0 h-9 w-9 p-0"
          @click="removePair(index)"
        >
          <X class="h-4 w-4" />
        </Button>
      </div>
    </div>

    <!-- Add button -->
    <Button
      type="button"
      variant="outline"
      size="sm"
      class="w-full"
      @click="addPair"
    >
      <Plus class="h-4 w-4 mr-2" />
      {{ translatedAddButtonLabel }}
    </Button>

    <!-- Helper text -->
    <p
      v-if="helperText"
      class="text-xs text-muted-foreground mt-1"
    >
      {{ helperText }}
    </p>
  </div>
</template>
