// resources/react/components/fields/ToggleButtons.tsx
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { resolveIcon } from '@laravilt/support/lib/icons';
import { useEffect, useRef, useState } from 'react';

interface Option {
    value: string | number;
    label: string;
    disabled?: boolean;
    icon?: string;
}

type ToggleValue = string | number | (string | number)[];

export interface ToggleButtonsProps {
    name?: string;
    value?: ToggleValue;
    modelValue?: ToggleValue;
    options: Option[];
    multiple?: boolean;
    inline?: boolean;
    disabled?: boolean;
    prefixIcon?: string;
    suffixIcon?: string;
    prefixIconColor?: string;
    suffixIconColor?: string;
    onUpdateModelValue?: (value: ToggleValue) => void;
    onUpdateValue?: (value: ToggleValue) => void;
    [key: string]: any;
}

// Helper to get Tailwind color classes for icons
const getIconColorClass = (color?: string) => {
    if (!color) return 'text-muted-foreground';

    // Map common color names to Tailwind classes
    const colorMap: Record<string, string> = {
        primary: 'text-primary',
        secondary: 'text-secondary',
        success: 'text-green-600',
        danger: 'text-red-600',
        warning: 'text-yellow-600',
        info: 'text-blue-600',
        muted: 'text-muted-foreground',
        destructive: 'text-destructive',
    };

    return colorMap[color] || 'text-muted-foreground';
};

export default function ToggleButtons({
    name,
    value,
    modelValue,
    options,
    multiple = false,
    inline = true,
    disabled = false,
    prefixIcon,
    suffixIcon,
    prefixIconColor,
    suffixIconColor,
    onUpdateModelValue,
    onUpdateValue,
}: ToggleButtonsProps) {
    const incoming = value ?? modelValue;

    // Internal state for the current value
    const [internalValue, setInternalValue] = useState<ToggleValue>(incoming ?? (multiple ? [] : ''));

    // Watch for prop changes and update internal state
    const previousIncoming = useRef(incoming);
    useEffect(() => {
        if (previousIncoming.current === incoming) return;
        previousIncoming.current = incoming;
        setInternalValue(incoming ?? (multiple ? [] : ''));
    }, [incoming, multiple]);

    // Use internal value for display and form submission
    const currentValue = internalValue;

    const isSelected = (optionValue: string | number) => {
        if (multiple && Array.isArray(internalValue)) {
            return internalValue.includes(optionValue);
        }
        return internalValue === optionValue;
    };

    const handleToggle = (optionValue: string | number) => {
        if (multiple) {
            const currentValues = Array.isArray(internalValue) ? internalValue : [];
            const newValue = currentValues.includes(optionValue)
                ? currentValues.filter((v) => v !== optionValue)
                : [...currentValues, optionValue];

            setInternalValue(newValue);
            onUpdateModelValue?.(newValue);
            onUpdateValue?.(newValue);
        } else {
            setInternalValue(optionValue);
            onUpdateModelValue?.(optionValue);
            onUpdateValue?.(optionValue);
        }
    };

    const PrefixIcon = resolveIcon(prefixIcon);
    const SuffixIcon = resolveIcon(suffixIcon);
    const optionList: Option[] = Array.isArray(options) ? options : Object.values(options || {});

    return (
        <div className="w-full space-y-2">
            {/* Hidden input for form submission */}
            {/* Multiple mode submits an array (`name[]`), matching the array the component emits */}
            {name &&
                (multiple ? (
                    (Array.isArray(currentValue) ? currentValue : []).map((item) => (
                        <input key={String(item)} type="hidden" name={`${name}[]`} value={String(item)} />
                    ))
                ) : (
                    <input type="hidden" name={name} value={String(currentValue ?? '')} />
                ))}

            {/* Header icons */}
            {(PrefixIcon || SuffixIcon) && (
                <div className="flex items-center justify-between">
                    {PrefixIcon && <PrefixIcon className={cn('h-4 w-4', getIconColorClass(prefixIconColor))} />}
                    {SuffixIcon && <SuffixIcon className={cn('h-4 w-4', getIconColorClass(suffixIconColor))} />}
                </div>
            )}

            {/* Button group */}
            <div className={cn('inline-flex rounded-md shadow-sm', inline ? 'flex-wrap gap-1' : 'flex-col gap-1')} role="group">
                {optionList.map((option) => {
                    const OptionIcon = resolveIcon(option.icon);
                    return (
                        <Button
                            key={option.value}
                            type="button"
                            variant={isSelected(option.value) ? 'default' : 'outline'}
                            disabled={disabled || option.disabled}
                            className="gap-2"
                            onClick={() => handleToggle(option.value)}
                        >
                            {OptionIcon && <OptionIcon className="h-4 w-4" />}
                            {option.label}
                        </Button>
                    );
                })}
            </div>
        </div>
    );
}

// resources/js/components/fields/ToggleButtons.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button'
import * as LucideIcons from 'lucide-vue-next'
import { computed, ref, watch } from 'vue'

interface Option {
  value: string | number
  label: string
  disabled?: boolean
  icon?: string
}

interface Props {
  name?: string
  value?: string | number | (string | number)[]
  modelValue?: string | number | (string | number)[]
  options: Option[]
  multiple?: boolean
  inline?: boolean
  disabled?: boolean
  prefixIcon?: string
  suffixIcon?: string
  prefixIconColor?: string
  suffixIconColor?: string
}

const props = withDefaults(defineProps<Props>(), {
  multiple: false,
  inline: true,
  disabled: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: string | number | (string | number)[]]
  'update:value': [value: string | number | (string | number)[]]
}>()

// Internal state for the current value
const internalValue = ref<string | number | (string | number)[]>(
  props.value ?? props.modelValue ?? (props.multiple ? [] : '')
)

// Watch for prop changes and update internal state
watch(() => props.value ?? props.modelValue, (newValue) => {
  internalValue.value = newValue ?? (props.multiple ? [] : '')
}, { immediate: true })

// Use internal value for display and form submission
const currentValue = computed(() => internalValue.value)

// Helper to get Lucide icon component by name
const getIconComponent = (iconName?: string) => {
  if (!iconName) return null
  // Convert kebab-case or lowercase to PascalCase for Lucide icons
  const pascalCase = iconName
    .split(/[-_\s]/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
  return (LucideIcons as any)[pascalCase] || null
}

// Helper to get Tailwind color classes for icons
const getIconColorClass = (color?: string) => {
  if (!color) return 'text-muted-foreground'

  // Map common color names to Tailwind classes
  const colorMap: Record<string, string> = {
    'primary': 'text-primary',
    'secondary': 'text-secondary',
    'success': 'text-green-600',
    'danger': 'text-red-600',
    'warning': 'text-yellow-600',
    'info': 'text-blue-600',
    'muted': 'text-muted-foreground',
    'destructive': 'text-destructive',
  }

  return colorMap[color] || 'text-muted-foreground'
}

const isSelected = (value: string | number) => {
  if (props.multiple && Array.isArray(internalValue.value)) {
    return internalValue.value.includes(value)
  }
  return internalValue.value === value
}

const handleToggle = (value: string | number) => {
  if (props.multiple) {
    const currentValues = Array.isArray(internalValue.value) ? internalValue.value : []
    const newValue = currentValues.includes(value)
      ? currentValues.filter(v => v !== value)
      : [...currentValues, value]

    internalValue.value = newValue
    emit('update:modelValue', newValue)
    emit('update:value', newValue)
  } else {
    internalValue.value = value
    emit('update:modelValue', value)
    emit('update:value', value)
  }
}
</script>

<template>
  <div class="w-full space-y-2">
    <!-- Hidden input for form submission -->
    <!-- Multiple mode submits an array (`name[]`), matching the array the component emits -->
    <template v-if="name">
      <template v-if="multiple">
        <input
          v-for="item in (Array.isArray(currentValue) ? currentValue : [])"
          :key="String(item)"
          type="hidden"
          :name="`${name}[]`"
          :value="item"
        />
      </template>
      <input
        v-else
        type="hidden"
        :name="name"
        :value="currentValue"
      />
    </template>

    <!-- Header icons -->
    <div v-if="getIconComponent(props.prefixIcon) || getIconComponent(props.suffixIcon)" class="flex items-center justify-between">
      <component
        v-if="getIconComponent(props.prefixIcon)"
        :is="getIconComponent(props.prefixIcon)"
        class="h-4 w-4"
        :class="getIconColorClass(props.prefixIconColor)"
      />
      <component
        v-if="getIconComponent(props.suffixIcon)"
        :is="getIconComponent(props.suffixIcon)"
        class="h-4 w-4"
        :class="getIconColorClass(props.suffixIconColor)"
      />
    </div>

    <!-- Button group -->
    <div
      class="inline-flex rounded-md shadow-sm"
      :class="inline ? 'flex-wrap gap-1' : 'flex-col gap-1'"
      role="group"
    >
      <Button
        v-for="option in options"
        :key="option.value"
        type="button"
        :variant="isSelected(option.value) ? 'default' : 'outline'"
        :disabled="disabled || option.disabled"
        class="gap-2"
        @click="handleToggle(option.value)"
      >
        <component
          v-if="getIconComponent(option.icon)"
          :is="getIconComponent(option.icon)"
          class="h-4 w-4"
        />
        {{ option.label }}
      </Button>
    </div>
  </div>
</template>
