// resources/js/components/schema/Tabs.vue
<template>
    <Tabs :default-value="String(activeTab || 0)" :dir="dir" class="w-full" @update:model-value="handleTabChange">
        <TabsList class="w-full justify-start">
            <TabsTrigger
                v-for="(tab, index) in tabs"
                :key="index"
                :value="String(index)"
                class="gap-2"
            >
                <component
                    v-if="tab.icon && getIconComponent(tab.icon)"
                    :is="getIconComponent(tab.icon)"
                    class="h-4 w-4"
                />
                <span>{{ tab.label }}</span>
                <span
                    v-if="tab.badge"
                    class="ms-1 inline-flex items-center justify-center px-2 py-0.5 text-xs font-medium rounded-full bg-primary/10 text-primary"
                >
                    {{ tab.badge }}
                </span>
            </TabsTrigger>
        </TabsList>

        <TabsContent
            v-for="(tab, index) in tabs"
            :key="index"
            :value="String(index)"
            class="space-y-6 mt-6"
        >
            <!-- Skeleton while loading -->
            <Transition
                enter-active-class="transition-opacity duration-150 ease-out"
                enter-from-class="opacity-0"
                enter-to-class="opacity-100"
                leave-active-class="transition-opacity duration-100 ease-in"
                leave-from-class="opacity-100"
                leave-to-class="opacity-0"
                mode="out-in"
            >
                <div v-if="isLoading && currentTab === String(index)" key="skeleton" class="space-y-6">
                    <div class="bg-card rounded-xl border shadow-sm p-6 space-y-4">
                        <div class="h-4 bg-muted/60 rounded w-1/4 animate-pulse"></div>
                        <div class="space-y-3">
                            <div class="h-10 bg-muted/60 rounded animate-pulse" style="animation-delay: 0ms"></div>
                            <div class="h-10 bg-muted/60 rounded animate-pulse" style="animation-delay: 75ms"></div>
                            <div class="h-10 bg-muted/60 rounded w-3/4 animate-pulse" style="animation-delay: 150ms"></div>
                        </div>
                    </div>
                </div>

                <!-- Actual content -->
                <!-- Rendered as a div: tabs already live inside the parent <form> -->
                <Form
                    v-else-if="tab.schema"
                    key="content"
                    as="div"
                    :schema="tab.schema"
                    :model-value="modelValue"
                    @update:model-value="(value) => emit('update:modelValue', value)"
                />
            </Transition>
        </TabsContent>
    </Tabs>
</template>

<script setup lang="ts">
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import Form from '../Form.vue'
import * as LucideIcons from 'lucide-vue-next'
import { ref, onMounted, onUnmounted, nextTick, Transition } from 'vue'

const props = defineProps<{
    tabs: Array<any>
    activeTab?: number
    persistTabInQueryString?: boolean
    modelValue?: Record<string, any>
}>()

const isLoading = ref(false)
const currentTab = ref(String(props.activeTab || 0))

const handleTabChange = async (value: string) => {
    if (value !== currentTab.value) {
        isLoading.value = true
        currentTab.value = value
        await nextTick()
        // Small delay to show skeleton
        setTimeout(() => {
            isLoading.value = false
        }, 150)
    }
}

// Reactive document direction for RTL support
const dir = ref<'ltr' | 'rtl'>('ltr')
let observer: MutationObserver | null = null

onMounted(() => {
    // Set initial direction
    dir.value = (document.documentElement.dir as 'ltr' | 'rtl') || 'ltr'

    // Watch for direction changes on the html element
    observer = new MutationObserver((mutations) => {
        for (const mutation of mutations) {
            if (mutation.attributeName === 'dir') {
                dir.value = (document.documentElement.dir as 'ltr' | 'rtl') || 'ltr'
            }
        }
    })

    observer.observe(document.documentElement, {
        attributes: true,
        attributeFilter: ['dir']
    })
})

onUnmounted(() => {
    if (observer) {
        observer.disconnect()
        observer = null
    }
})

const emit = defineEmits<{
    'update:modelValue': [value: Record<string, any>]
}>()

// Convert kebab-case or snake_case icon names to PascalCase for lucide-vue-next
const getIconComponent = (iconName: string) => {
    if (!iconName) return null

    // Convert formats like 'user', 'file-text', 'user-circle' to PascalCase
    const pascalCase = iconName
        .split(/[-_]/)
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join('')

    return (LucideIcons as any)[pascalCase] || null
}
</script>

// resources/react/components/schema/Tabs.tsx
import { Tabs as UiTabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { resolveIcon } from '@laravilt/support/lib/icons';
import { useEffect, useRef, useState } from 'react';
import Form from '../Form';

export interface TabsProps {
    tabs: Array<any>;
    activeTab?: number;
    persistTabInQueryString?: boolean;
    modelValue?: Record<string, any>;
    onUpdateModelValue?: (value: Record<string, any>) => void;
    [key: string]: any;
}

export default function Tabs({ tabs, activeTab, modelValue, onUpdateModelValue }: TabsProps) {
    const [isLoading, setIsLoading] = useState(false);
    const [currentTab, setCurrentTab] = useState(String(activeTab || 0));
    const loadingTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

    const handleTabChange = (value: string) => {
        if (value !== currentTab) {
            setIsLoading(true);
            setCurrentTab(value);
            // Small delay to show skeleton
            if (loadingTimeout.current) clearTimeout(loadingTimeout.current);
            loadingTimeout.current = setTimeout(() => {
                setIsLoading(false);
            }, 150);
        }
    };

    // Reactive document direction for RTL support
    const [dir, setDir] = useState<'ltr' | 'rtl'>('ltr');

    useEffect(() => {
        // Set initial direction
        setDir((document.documentElement.dir as 'ltr' | 'rtl') || 'ltr');

        // Watch for direction changes on the html element
        const observer = new MutationObserver((mutations) => {
            for (const mutation of mutations) {
                if (mutation.attributeName === 'dir') {
                    setDir((document.documentElement.dir as 'ltr' | 'rtl') || 'ltr');
                }
            }
        });

        observer.observe(document.documentElement, {
            attributes: true,
            attributeFilter: ['dir'],
        });

        return () => {
            observer.disconnect();
            if (loadingTimeout.current) clearTimeout(loadingTimeout.current);
        };
    }, []);

    return (
        <UiTabs defaultValue={String(activeTab || 0)} dir={dir} className="w-full" onValueChange={handleTabChange}>
            <TabsList className="w-full justify-start">
                {(tabs || []).map((tab: any, index: number) => {
                    const TabIcon = tab.icon ? resolveIcon(tab.icon) : null;
                    return (
                        <TabsTrigger key={index} value={String(index)} className="gap-2">
                            {tab.icon && TabIcon && <TabIcon className="h-4 w-4" />}
                            <span>{tab.label}</span>
                            {tab.badge && (
                                <span className="ms-1 inline-flex items-center justify-center px-2 py-0.5 text-xs font-medium rounded-full bg-primary/10 text-primary">
                                    {tab.badge}
                                </span>
                            )}
                        </TabsTrigger>
                    );
                })}
            </TabsList>

            {(tabs || []).map((tab: any, index: number) => (
                <TabsContent key={index} value={String(index)} className="space-y-6 mt-6">
                    {/* Skeleton while loading */}
                    {isLoading && currentTab === String(index) ? (
                        <div key="skeleton" className="space-y-6 transition-opacity duration-150 ease-out animate-in fade-in-0">
                            <div className="bg-card rounded-xl border shadow-sm p-6 space-y-4">
                                <div className="h-4 bg-muted/60 rounded w-1/4 animate-pulse"></div>
                                <div className="space-y-3">
                                    <div className="h-10 bg-muted/60 rounded animate-pulse" style={{ animationDelay: '0ms' }}></div>
                                    <div className="h-10 bg-muted/60 rounded animate-pulse" style={{ animationDelay: '75ms' }}></div>
                                    <div className="h-10 bg-muted/60 rounded w-3/4 animate-pulse" style={{ animationDelay: '150ms' }}></div>
                                </div>
                            </div>
                        </div>
                    ) : tab.schema ? (
                        /* Actual content (a div: tabs already live inside the parent <form>) */
                        <Form
                            key="content"
                            as="div"
                            schema={tab.schema}
                            modelValue={modelValue}
                            onUpdateModelValue={(value) => onUpdateModelValue?.(value)}
                        />
                    ) : null}
                </TabsContent>
            ))}
        </UiTabs>
    );
}
