// resources/js/components/Form.vue
<template>
    <component :is="as" ref="formRef" :class="containerClass" @submit.prevent>
        <template v-for="(component, index) in internalSchema" :key="component.name || component.id || index">
            <!-- Group consecutive actions together (only render on first action in group) -->
            <div v-if="isAction(component) && !isPreviousItemAction(index) && isNextItemAction(index)" class="flex flex-wrap gap-2 items-start">
                <FormActionButton
                    v-bind="component"
                    :getFormData="getFormData"
                />
                <template v-for="(nextComponent, nextIndex) in getConsecutiveActions(index)" :key="nextComponent.name || nextComponent.id || (index + nextIndex + 1)">
                    <FormActionButton
                        v-bind="nextComponent"
                        :getFormData="getFormData"
                    />
                </template>
            </div>

            <!-- Render single action (not part of a group) -->
            <FormActionButton
                v-else-if="isAction(component) && !isPreviousItemAction(index) && !isNextItemAction(index)"
                v-bind="component"
                :getFormData="getFormData"
            />

            <!-- Render regular form components -->
            <component
                v-else-if="!isAction(component)"
                :is="getComponent(component)"
                v-bind="getComponentProps(component)"
                :value="isSchemaComponent(component) ? undefined : internalFormData[component.name]"
                :model-value="isSchemaComponent(component) ? internalFormData : internalFormData[component.name]"
                :disabled="disabled || component.disabled"
                :error="getError(component)"
                @update:model-value="(value) => handleComponentUpdate(component, value)"
            />
        </template>
    </component>
</template>

<script setup lang="ts">
import { defineAsyncComponent, onMounted, onUnmounted, computed, h, ref, watch, provide, inject, nextTick } from 'vue'
import ActionButton from '@laravilt/actions/components/ActionButton.vue'

// Import commonly used components directly for faster modal/form load
import Grid from './schema/Grid.vue'
import Section from './schema/Section.vue'
import TextInput from './fields/TextInput.vue'
import Textarea from './fields/Textarea.vue'
import Toggle from './fields/Toggle.vue'
import Checkbox from './fields/Checkbox.vue'
import CheckboxList from './fields/CheckboxList.vue'
import Select from './fields/Select.vue'
import Hidden from './fields/Hidden.vue'

// A <form>, or a <div> when nested inside another form (e.g. tab content) since nested forms are invalid HTML
const formRef = ref<HTMLElement | null>(null)
const internalFormData = ref<Record<string, any>>({})

// Local validation errors for client-side validation
const localErrors = ref<Record<string, string>>({})

// Inject errors from ErrorProvider (it's a computed ref)
const injectedErrors = inject<any>('errors', {})

// Merged errors: local client-side errors + server-side errors
const errors = computed(() => {
    const serverErrors = injectedErrors?.value || injectedErrors || {}
    return { ...localErrors.value, ...serverErrors }
})

// Create a wrapper component for form actions that can collect form data
const FormActionButton = {
    props: {
        getFormData: Function,
    },
    setup(props: any, { attrs }: any) {
        return () => h(ActionButton, {
            ...attrs,
            getFormData: props.getFormData,
        })
    },
}

const props = withDefaults(defineProps<{
    schema: Array<any>
    modelValue?: Record<string, any>
    schemaId?: string
    disabled?: boolean
    formController?: string
    formMethod?: string
    as?: 'form' | 'div'
}>(), {
    formController: undefined,
    formMethod: 'getSchema',
    as: 'form',
})

const emit = defineEmits<{
    'update:modelValue': [value: Record<string, any>]
    'update:schema': [value: any[]]
}>()

// Make schema internally reactive so it can be updated by reactive fields
const internalSchema = ref(props.schema)

// Watch for prop schema changes (from page navigation, etc.)
watch(() => props.schema, (newSchema) => {
    internalSchema.value = newSchema
})

// Recursively extract all field components and their default values from schema
const extractFieldDefaults = (schema: Array<any>): Record<string, any> => {
    const defaults: Record<string, any> = {}
    const schemaComponentTypes = ['tabs', 'section', 'grid']

    // Safety check - ensure schema is an array
    if (!schema || !Array.isArray(schema)) {
        console.warn('extractFieldDefaults: schema is not an array', schema)
        return defaults
    }

    for (const component of schema) {
        // Skip actions
        if (component.hasAction === true || (component.name && !component.component)) {
            continue
        }

        // If it's a tabs component, extract from all tabs
        if (component.component === 'tabs' && component.tabs && Array.isArray(component.tabs)) {
            for (const tab of component.tabs) {
                if (tab.schema && Array.isArray(tab.schema)) {
                    Object.assign(defaults, extractFieldDefaults(tab.schema))
                }
            }
            continue // Don't add the tabs component itself as a field
        }

        // If it's a schema component (section, grid), recurse into its schema
        if (schemaComponentTypes.includes(component.component) && component.schema && Array.isArray(component.schema)) {
            Object.assign(defaults, extractFieldDefaults(component.schema))
            continue // Don't add the schema component itself as a field
        }

        // If it has a name and component type (it's an actual field), add its default value
        if (component.name && component.component && !schemaComponentTypes.includes(component.component)) {
            // Use defaultValue or default, but NOT value (value could be an object from backend)
            // For hidden fields, also check the 'default' property
            // Use ?? (nullish coalescing) to properly handle false/0 values
            defaults[component.name] = component.defaultValue ?? component.default ?? component.value ?? null
        }
    }

    return defaults
}

// Initialize form data with defaults from schema
// Note: The watcher with immediate: true handles initial modelValue merging
const initializeFormData = () => {
    // Only initialize with defaults if modelValue is empty
    // The watcher handles cases where modelValue is provided
    if (!props.modelValue || Object.keys(props.modelValue).length === 0) {
        const defaults = extractFieldDefaults(internalSchema.value)
        internalFormData.value = { ...defaults }
        emit('update:modelValue', internalFormData.value)
    }
}

// Handle action-updated data events
const handleActionUpdatedData = (event: CustomEvent) => {
    const updatedData = event.detail;

    if (updatedData && typeof updatedData === 'object') {
        // Merge the updated data into internal form data
        internalFormData.value = {
            ...internalFormData.value,
            ...updatedData
        };
        emit('update:modelValue', internalFormData.value);
    }
};

// Initialize on mount
onMounted(() => {
    initializeFormData();

    // Listen for action-updated-data events from ActionButton
    window.addEventListener('action-updated-data', handleActionUpdatedData as EventListener);
});

// Cleanup on unmount
onUnmounted(() => {
    window.removeEventListener('action-updated-data', handleActionUpdatedData as EventListener);
});

// Watch for internal schema changes (from reactive fields)
// Don't re-initialize form data as it will reset user input
// The schema update only changes field options, not the data itself
watch(internalSchema, () => {
    // Intentionally empty - we don't need to do anything when schema changes
    // The reactive update already handles option changes
}, { deep: true })

// Whether the last modelValue had data. A parent that passes a fresh `{}` on every render must not
// wipe user input, so only a genuine change from data to empty resets the form.
let modelHadData = false

// Watch for external modelValue changes and merge them
// Use immediate: true to handle initial value properly (important for edit/view modals)
watch(() => props.modelValue, (newValue) => {
    const hasData = !!newValue && Object.keys(newValue).length > 0

    if (hasData) {
        // Get defaults from schema
        const defaults = extractFieldDefaults(internalSchema.value)
        // Merge defaults with new value - new value takes precedence
        internalFormData.value = {
            ...defaults,
            ...newValue
        }
    } else if (modelHadData) {
        // The parent cleared the model (e.g. after submit): reset to the schema defaults
        internalFormData.value = { ...extractFieldDefaults(internalSchema.value) }
        localErrors.value = {}
        emit('update:modelValue', internalFormData.value)
    }

    modelHadData = hasData
}, { deep: true, immediate: true })

// Handle component update events
const handleComponentUpdate = async (component: any, value: any) => {
    if (isSchemaComponent(component)) {
        // For schema components (Section, Grid, Tabs), value is an object with field updates
        // Update internal form data first
        const oldData = { ...internalFormData.value }

        // Check if any values actually changed before proceeding
        let hasChanges = false
        for (const [fieldName, fieldValue] of Object.entries(value)) {
            if (oldData[fieldName] !== fieldValue) {
                hasChanges = true
                break
            }
        }

        // Skip if nothing changed (performance optimization)
        if (!hasChanges) {
            return
        }

        internalFormData.value = { ...internalFormData.value, ...value }
        emit('update:modelValue', internalFormData.value)

        // Check each field that changed for reactivity
        for (const [fieldName, fieldValue] of Object.entries(value)) {
            // Only trigger if value actually changed
            if (oldData[fieldName] !== fieldValue) {
                // Find the field in schema and check if it's reactive
                const field = findFieldInSchema(internalSchema.value, fieldName)
                if (field && (field.isLive || field.isLazy)) {
                    await triggerReactiveFieldUpdate(fieldName, field)
                }
            }
        }
    } else {
        await updateValue(component.name, value)
    }
}

const updateValue = async (name: string, value: any) => {
    // Update internal form data
    internalFormData.value = {
        ...internalFormData.value,
        [name]: value
    }

    emit('update:modelValue', internalFormData.value)

    // Check if this field is reactive (live/lazy)
    const field = findFieldInSchema(internalSchema.value, name)

    if (field && (field.isLive || field.isLazy)) {
        await triggerReactiveFieldUpdate(name, field)
    }
}

// Find a field by name in the schema (recursively)
const findFieldInSchema = (schema: any[], fieldName: string): any => {
    for (const component of schema) {
        if (component.name === fieldName) {
            return component
        }

        // Check nested schemas
        if (component.component === 'tabs' && component.tabs) {
            for (const tab of component.tabs) {
                if (tab.schema) {
                    const found = findFieldInSchema(tab.schema, fieldName)
                    if (found) return found
                }
            }
        }

        if (component.schema) {
            const found = findFieldInSchema(component.schema, fieldName)
            if (found) return found
        }
    }
    return null
}

// Sequence number of the latest reactive request; older responses that finish later are ignored
let reactiveRequestSeq = 0

// Trigger reactive field update
const triggerReactiveFieldUpdate = async (fieldName: string, field: any) => {
    // Skip if no form controller is configured
    if (!props.formController) {
        console.warn('[Form] No formController configured, skipping reactive field update')
        return
    }

    const requestId = ++reactiveRequestSeq

    const debounceMs = field.isLazy
        ? (field.liveDebounce || 500)
        : (field.isLive && field.liveDebounce ? field.liveDebounce : 0)

    // TODO: Implement debouncing if needed
    try {
        const payload = {
            controller: props.formController,
            method: props.formMethod || 'getSchema',
            data: internalFormData.value,
            changed_field: fieldName,
        }

        const response = await fetch('/reactive-fields/update', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || '',
            },
            body: JSON.stringify(payload),
        })

        if (!response.ok) {
            throw new Error('Failed to update reactive fields')
        }

        const result = await response.json()

        // A newer reactive request started while this one was in flight; its response wins
        if (requestId !== reactiveRequestSeq) {
            return
        }

        if (result.schema) {
            updateSchema(result.schema)
        }

        // Update form data if backend modified it (from afterStateUpdated)
        if (result.data) {
            internalFormData.value = { ...internalFormData.value, ...result.data }
            emit('update:modelValue', internalFormData.value)
        }
    } catch (error) {
        console.error('[FormRenderer] Error updating reactive fields:', error)
    }
}

// Collect all form data - just return the internal tracked data
const getFormData = () => {
    // Return a copy to avoid mutations
    return { ...internalFormData.value }
}

// Extract required fields from schema recursively
const extractRequiredFields = (schema: Array<any>): Array<{ name: string; label: string }> => {
    const requiredFields: Array<{ name: string; label: string }> = []
    const schemaComponentTypes = ['tabs', 'section', 'grid']

    if (!schema || !Array.isArray(schema)) {
        return requiredFields
    }

    for (const component of schema) {
        // Skip actions
        if (component.hasAction === true || (component.name && !component.component)) {
            continue
        }

        // If it's a tabs component, extract from all tabs
        if (component.component === 'tabs' && component.tabs && Array.isArray(component.tabs)) {
            for (const tab of component.tabs) {
                if (tab.schema && Array.isArray(tab.schema)) {
                    requiredFields.push(...extractRequiredFields(tab.schema))
                }
            }
            continue
        }

        // If it's a schema component (section, grid), recurse into its schema
        if (schemaComponentTypes.includes(component.component) && component.schema && Array.isArray(component.schema)) {
            requiredFields.push(...extractRequiredFields(component.schema))
            continue
        }

        // If it has a name and is required, add to the list
        if (component.name && component.required) {
            requiredFields.push({
                name: component.name,
                label: component.label || component.name
            })
        }
    }

    return requiredFields
}

// Check if a value is empty (null, undefined, empty string, empty array)
const isValueEmpty = (value: any): boolean => {
    if (value === null || value === undefined) return true
    if (typeof value === 'string' && value.trim() === '') return true
    if (Array.isArray(value) && value.length === 0) return true
    return false
}

// Validate the form - combines HTML5 validation with custom required field checks
const validateForm = () => {
    // Clear previous local validation errors
    localErrors.value = {}

    // Get all required fields from schema
    const requiredFields = extractRequiredFields(internalSchema.value)

    // Check each required field
    const newErrors: Record<string, string> = {}
    for (const field of requiredFields) {
        const value = internalFormData.value[field.name]
        if (isValueEmpty(value)) {
            newErrors[field.name] = `${field.label} is required.`
        }
    }

    // If there are validation errors, set them and return false
    if (Object.keys(newErrors).length > 0) {
        localErrors.value = newErrors
        return false
    }

    // Also run HTML5 validation for native form elements
    if (formRef.value instanceof HTMLFormElement) {
        const isHtml5Valid = formRef.value.checkValidity()
        if (!isHtml5Valid) {
            formRef.value.reportValidity()
            return false
        }
    }

    return true
}

// Clear local validation errors (useful when modal closes or form resets)
const clearValidationErrors = () => {
    localErrors.value = {}
}

// Function to update schema (for reactive fields)
const updateSchema = (newSchema: any[]) => {
    // Save current scroll position and focused element
    const scrollX = window.scrollX
    const scrollY = window.scrollY
    const activeElement = document.activeElement as HTMLElement

    // Simply update the schema - Vue's reactivity will handle the updates
    // Since we're using ref(), Vue will detect the change
    internalSchema.value = newSchema

    // Restore scroll position and focus immediately in next tick
    nextTick(() => {
        // Restore scroll position
        window.scrollTo({
            top: scrollY,
            left: scrollX,
            behavior: 'instant' as ScrollBehavior
        })

        // Restore focus if element still exists
        if (activeElement && document.contains(activeElement)) {
            activeElement.focus({ preventScroll: true })
        }
    })
}

// Provide getFormData, validateForm, updateSchema, schemaId, formController, and errors to all child components
provide('getFormData', getFormData)
provide('validateForm', validateForm)
provide('updateSchema', updateSchema)
provide('schemaId', props.schemaId || null)
provide('formController', props.formController)
provide('formMethod', props.formMethod)
// Override the errors provided by ErrorProvider with our merged errors (local + server)
provide('errors', errors)

// Expose getFormData, validateForm, and clearValidationErrors to parent components via template ref
defineExpose({
    getFormData,
    validateForm,
    clearValidationErrors
})

// Check if an item is an action
const isAction = (item: any) => {
    // Actions have hasAction property or don't have a component property
    return item.hasAction === true || (item.name && !item.component)
}

// Check if the next item is an action
const isNextItemAction = (index: number) => {
    const nextItem = internalSchema.value[index + 1]
    return nextItem && isAction(nextItem)
}

// Check if the previous item is an action
const isPreviousItemAction = (index: number) => {
    const prevItem = internalSchema.value[index - 1]
    return prevItem && isAction(prevItem)
}

// Get all consecutive actions starting from the next index
const getConsecutiveActions = (startIndex: number) => {
    const actions = []
    let currentIndex = startIndex + 1

    while (currentIndex < internalSchema.value.length && isAction(internalSchema.value[currentIndex])) {
        actions.push(internalSchema.value[currentIndex])
        currentIndex++
    }

    return actions
}

// Check if a component is a schema component (needs entire modelValue, not just a field value)
const isSchemaComponent = (component: any) => {
    const schemaComponents = ['tabs', 'section', 'grid']
    return schemaComponents.includes(component.component)
}

// Determine container spacing based on what we're rendering
const containerClass = computed(() => {
    if (!internalSchema.value || !Array.isArray(internalSchema.value) || internalSchema.value.length === 0) return ''

    // Check if we're rendering sections - if so, use space-y-12
    const hasSections = internalSchema.value.some(c => c.component === 'section')
    if (hasSections) return 'space-y-12'

    // Otherwise use space-y-6 for general spacing
    return 'space-y-6'
})

const toLaraviltName = (name: any) => {
  if (!name) return
  return 'laravilt-' + name.replaceAll('_', '-')
}

const getComponent = (component: any) => {
  return toLaraviltName(component.component) || 'div'
}

// Get component props, excluding value, modelValue, and disabled since we set them explicitly
const getComponentProps = (component: any) => {
    const { value, modelValue, disabled, ...rest } = component
    return rest
}

// Get error message for a component
const getError = (component: any) => {
    // errors is a computed ref, access its value
    const errorsObj = errors.value
    if (!component.name || !errorsObj) return undefined
    const error = errorsObj[component.name]
    return Array.isArray(error) ? error[0] : error
}
</script>

// resources/react/components/Form.tsx
import ActionButton from '@laravilt/actions/components/ActionButton';
import { ErrorsContext, SchemaContext, useErrors, type SchemaContextValue } from '@laravilt/support/composables/contexts';
import { useLatest } from '@laravilt/support/composables/hooks';
import { resolveComponent } from '@laravilt/support/composables/registry';
import { Fragment, useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState, type FormEvent, type Ref } from 'react';

export interface FormHandle {
    getFormData(): Record<string, any>;
    validateForm(): boolean;
    clearValidationErrors(): void;
}

export interface FormProps {
    schema: Array<any>;
    modelValue?: Record<string, any>;
    schemaId?: string;
    disabled?: boolean;
    formController?: string;
    formMethod?: string;
    /** Render a <div> instead of a <form> when nested inside another form (nested forms are invalid HTML). */
    as?: 'form' | 'div';
    onUpdateModelValue?: (value: Record<string, any>) => void;
    onUpdateSchema?: (value: any[]) => void;
    ref?: Ref<FormHandle>;
}

const schemaComponentTypes = ['tabs', 'section', 'grid'];

// Recursively extract all field components and their default values from schema
const extractFieldDefaults = (schema: Array<any>): Record<string, any> => {
    const defaults: Record<string, any> = {};

    // Safety check - ensure schema is an array
    if (!schema || !Array.isArray(schema)) {
        console.warn('extractFieldDefaults: schema is not an array', schema);
        return defaults;
    }

    for (const component of schema) {
        // Skip actions
        if (component.hasAction === true || (component.name && !component.component)) {
            continue;
        }

        // If it's a tabs component, extract from all tabs
        if (component.component === 'tabs' && component.tabs && Array.isArray(component.tabs)) {
            for (const tab of component.tabs) {
                if (tab.schema && Array.isArray(tab.schema)) {
                    Object.assign(defaults, extractFieldDefaults(tab.schema));
                }
            }
            continue; // Don't add the tabs component itself as a field
        }

        // If it's a schema component (section, grid), recurse into its schema
        if (schemaComponentTypes.includes(component.component) && component.schema && Array.isArray(component.schema)) {
            Object.assign(defaults, extractFieldDefaults(component.schema));
            continue; // Don't add the schema component itself as a field
        }

        // If it has a name and component type (it's an actual field), add its default value
        if (component.name && component.component && !schemaComponentTypes.includes(component.component)) {
            // Use defaultValue or default, but NOT value (value could be an object from backend)
            // Use ?? (nullish coalescing) to properly handle false/0 values
            defaults[component.name] = component.defaultValue ?? component.default ?? component.value ?? null;
        }
    }

    return defaults;
};

// Extract required fields from schema recursively
const extractRequiredFields = (schema: Array<any>): Array<{ name: string; label: string }> => {
    const requiredFields: Array<{ name: string; label: string }> = [];

    if (!schema || !Array.isArray(schema)) {
        return requiredFields;
    }

    for (const component of schema) {
        // Skip actions
        if (component.hasAction === true || (component.name && !component.component)) {
            continue;
        }

        // If it's a tabs component, extract from all tabs
        if (component.component === 'tabs' && component.tabs && Array.isArray(component.tabs)) {
            for (const tab of component.tabs) {
                if (tab.schema && Array.isArray(tab.schema)) {
                    requiredFields.push(...extractRequiredFields(tab.schema));
                }
            }
            continue;
        }

        // If it's a schema component (section, grid), recurse into its schema
        if (schemaComponentTypes.includes(component.component) && component.schema && Array.isArray(component.schema)) {
            requiredFields.push(...extractRequiredFields(component.schema));
            continue;
        }

        // If it has a name and is required, add to the list
        if (component.name && component.required) {
            requiredFields.push({
                name: component.name,
                label: component.label || component.name,
            });
        }
    }

    return requiredFields;
};

// Find a field by name in the schema (recursively)
const findFieldInSchema = (schema: any[], fieldName: string): any => {
    for (const component of schema) {
        if (component.name === fieldName) {
            return component;
        }

        // Check nested schemas
        if (component.component === 'tabs' && component.tabs) {
            for (const tab of component.tabs) {
                if (tab.schema) {
                    const found = findFieldInSchema(tab.schema, fieldName);
                    if (found) return found;
                }
            }
        }

        if (component.schema) {
            const found = findFieldInSchema(component.schema, fieldName);
            if (found) return found;
        }
    }
    return null;
};

// Check if a value is empty (null, undefined, empty string, empty array)
const isValueEmpty = (value: any): boolean => {
    if (value === null || value === undefined) return true;
    if (typeof value === 'string' && value.trim() === '') return true;
    if (Array.isArray(value) && value.length === 0) return true;
    return false;
};

// Check if an item is an action
const isAction = (item: any) => {
    // Actions have hasAction property or don't have a component property
    return item.hasAction === true || (item.name && !item.component);
};

// Check if a component is a schema component (needs entire modelValue, not just a field value)
const isSchemaComponent = (component: any) => {
    return schemaComponentTypes.includes(component.component);
};

const toLaraviltName = (name: any) => {
    if (!name) return;
    return 'laravilt-' + String(name).replaceAll('_', '-');
};

// Get component props, excluding value, modelValue, and disabled since we set them explicitly
const getComponentProps = (component: any) => {
    const { value, modelValue, disabled, ...rest } = component;
    return rest;
};

export default function Form({
    schema,
    modelValue,
    schemaId,
    disabled,
    formController = undefined,
    formMethod = 'getSchema',
    as = 'form',
    onUpdateModelValue,
    ref,
}: FormProps) {
    const formRef = useRef<HTMLElement | null>(null);
    const setFormElement = useCallback((element: HTMLElement | null) => {
        formRef.current = element;
    }, []);

    // Make schema internally reactive so it can be updated by reactive fields
    const [internalSchema, setInternalSchemaState] = useState<any[]>(schema);
    const internalSchemaRef = useRef<any[]>(schema);
    const setInternalSchema = (next: any[]) => {
        internalSchemaRef.current = next;
        setInternalSchemaState(next);
    };

    // Form data (state for rendering + ref for synchronous reads, like Vue's `.value`)
    // Initial value mirrors the immediate modelValue watcher
    const [internalFormData, setInternalFormDataState] = useState<Record<string, any>>(() =>
        modelValue && Object.keys(modelValue).length > 0 ? { ...extractFieldDefaults(schema), ...modelValue } : {},
    );
    const internalFormDataRef = useRef<Record<string, any>>(internalFormData);
    const setInternalFormData = (next: Record<string, any>) => {
        internalFormDataRef.current = next;
        setInternalFormDataState(next);
    };

    const latest = useLatest({ onUpdateModelValue, formController, formMethod });
    const emitModelValue = (value: Record<string, any>) => latest.current.onUpdateModelValue?.(value);

    // Local validation errors for client-side validation
    const [localErrors, setLocalErrors] = useState<Record<string, string>>({});

    // Errors from ErrorProvider
    const injectedErrors = useErrors();

    // Merged errors: local client-side errors + server-side errors
    const errors = useMemo(() => ({ ...localErrors, ...(injectedErrors || {}) }), [localErrors, injectedErrors]);

    // Watch for prop schema changes (from page navigation, etc.)
    const previousSchema = useRef(schema);
    useEffect(() => {
        if (previousSchema.current === schema) return;
        previousSchema.current = schema;
        setInternalSchema(schema);
    }, [schema]);

    // Watch for external modelValue changes and merge them
    const previousModelValue = useRef(modelValue);
    // Whether the last modelValue had data. A parent that passes a fresh `{}` on every render must not
    // wipe user input, so only a genuine change from data to empty resets the form.
    const modelHadData = useRef(!!modelValue && Object.keys(modelValue).length > 0);
    useEffect(() => {
        if (previousModelValue.current === modelValue) return;
        previousModelValue.current = modelValue;

        const hasData = !!modelValue && Object.keys(modelValue).length > 0;

        if (hasData) {
            // Get defaults from schema
            const defaults = extractFieldDefaults(internalSchemaRef.current);
            // Merge defaults with new value - new value takes precedence
            setInternalFormData({
                ...defaults,
                ...modelValue,
            });
        } else if (modelHadData.current) {
            // The parent cleared the model (e.g. after submit): reset to the schema defaults
            setInternalFormData({ ...extractFieldDefaults(internalSchemaRef.current) });
            setLocalErrors({});
            emitModelValue(internalFormDataRef.current);
        }

        modelHadData.current = hasData;
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [modelValue]);

    // Initialize on mount + listen for action-updated-data events from ActionButton
    const latestModelValue = useLatest(modelValue);
    useEffect(() => {
        // Only initialize with defaults if modelValue is empty
        const currentModelValue = latestModelValue.current;
        if (!currentModelValue || Object.keys(currentModelValue).length === 0) {
            const defaults = extractFieldDefaults(internalSchemaRef.current);
            setInternalFormData({ ...defaults });
            emitModelValue(internalFormDataRef.current);
        }

        // Handle action-updated data events
        const handleActionUpdatedData = (event: Event) => {
            const updatedData = (event as CustomEvent).detail;

            if (updatedData && typeof updatedData === 'object') {
                // Merge the updated data into internal form data
                setInternalFormData({
                    ...internalFormDataRef.current,
                    ...updatedData,
                });
                emitModelValue(internalFormDataRef.current);
            }
        };

        window.addEventListener('action-updated-data', handleActionUpdatedData);

        return () => {
            window.removeEventListener('action-updated-data', handleActionUpdatedData);
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    // Function to update schema (for reactive fields)
    const pendingRestore = useRef<{ scrollX: number; scrollY: number; activeElement: HTMLElement | null } | null>(null);
    const updateSchema = useCallback((newSchema: any[]) => {
        // Save current scroll position and focused element
        pendingRestore.current = {
            scrollX: window.scrollX,
            scrollY: window.scrollY,
            activeElement: document.activeElement as HTMLElement,
        };

        setInternalSchema(newSchema);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    // Restore scroll position and focus after the schema re-render (Vue: nextTick)
    useEffect(() => {
        const restore = pendingRestore.current;
        if (!restore) return;
        pendingRestore.current = null;

        window.scrollTo({
            top: restore.scrollY,
            left: restore.scrollX,
            behavior: 'instant' as ScrollBehavior,
        });

        // Restore focus if element still exists
        if (restore.activeElement && document.contains(restore.activeElement)) {
            restore.activeElement.focus({ preventScroll: true });
        }
    }, [internalSchema]);

    // Sequence number of the latest reactive request; older responses that finish later are ignored
    const reactiveRequestSeq = useRef(0);

    // Trigger reactive field update
    const triggerReactiveFieldUpdate = async (fieldName: string, _field: any) => {
        const { formController: controller, formMethod: method } = latest.current;

        // Skip if no form controller is configured
        if (!controller) {
            console.warn('[Form] No formController configured, skipping reactive field update');
            return;
        }

        const requestId = ++reactiveRequestSeq.current;

        // TODO (from Vue): Implement debouncing if needed
        try {
            const payload = {
                controller,
                method: method || 'getSchema',
                data: internalFormDataRef.current,
                changed_field: fieldName,
            };

            const response = await fetch('/reactive-fields/update', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || '',
                },
                body: JSON.stringify(payload),
            });

            if (!response.ok) {
                throw new Error('Failed to update reactive fields');
            }

            const result = await response.json();

            // A newer reactive request started while this one was in flight; its response wins
            if (requestId !== reactiveRequestSeq.current) {
                return;
            }

            if (result.schema) {
                updateSchema(result.schema);
            }

            // Update form data if backend modified it (from afterStateUpdated)
            if (result.data) {
                setInternalFormData({ ...internalFormDataRef.current, ...result.data });
                emitModelValue(internalFormDataRef.current);
            }
        } catch (error) {
            console.error('[FormRenderer] Error updating reactive fields:', error);
        }
    };

    const updateValue = async (name: string, value: any) => {
        // Update internal form data
        setInternalFormData({
            ...internalFormDataRef.current,
            [name]: value,
        });

        emitModelValue(internalFormDataRef.current);

        // Check if this field is reactive (live/lazy)
        const field = findFieldInSchema(internalSchemaRef.current, name);

        if (field && (field.isLive || field.isLazy)) {
            await triggerReactiveFieldUpdate(name, field);
        }
    };

    // Handle component update events
    const handleComponentUpdate = async (component: any, value: any) => {
        if (isSchemaComponent(component)) {
            // For schema components (Section, Grid, Tabs), value is an object with field updates
            const oldData = { ...internalFormDataRef.current };

            // Check if any values actually changed before proceeding
            let hasChanges = false;
            for (const [fieldName, fieldValue] of Object.entries(value || {})) {
                if (oldData[fieldName] !== fieldValue) {
                    hasChanges = true;
                    break;
                }
            }

            // Skip if nothing changed (performance optimization)
            if (!hasChanges) {
                return;
            }

            setInternalFormData({ ...internalFormDataRef.current, ...value });
            emitModelValue(internalFormDataRef.current);

            // Check each field that changed for reactivity
            for (const [fieldName, fieldValue] of Object.entries(value)) {
                // Only trigger if value actually changed
                if (oldData[fieldName] !== fieldValue) {
                    // Find the field in schema and check if it's reactive
                    const field = findFieldInSchema(internalSchemaRef.current, fieldName);
                    if (field && (field.isLive || field.isLazy)) {
                        await triggerReactiveFieldUpdate(fieldName, field);
                    }
                }
            }
        } else {
            await updateValue(component.name, value);
        }
    };

    // Collect all form data - just return the internal tracked data
    const getFormData = useCallback(() => {
        // Return a copy to avoid mutations
        return { ...internalFormDataRef.current };
    }, []);

    // Validate the form - combines HTML5 validation with custom required field checks
    const validateForm = useCallback(() => {
        // Clear previous local validation errors
        setLocalErrors({});

        // Get all required fields from schema
        const requiredFields = extractRequiredFields(internalSchemaRef.current);

        // Check each required field
        const newErrors: Record<string, string> = {};
        for (const field of requiredFields) {
            const value = internalFormDataRef.current[field.name];
            if (isValueEmpty(value)) {
                newErrors[field.name] = `${field.label} is required.`;
            }
        }

        // If there are validation errors, set them and return false
        if (Object.keys(newErrors).length > 0) {
            setLocalErrors(newErrors);
            return false;
        }

        // Also run HTML5 validation for native form elements
        if (formRef.current instanceof HTMLFormElement) {
            const isHtml5Valid = formRef.current.checkValidity();
            if (!isHtml5Valid) {
                formRef.current.reportValidity();
                return false;
            }
        }

        return true;
    }, []);

    // Clear local validation errors (useful when modal closes or form resets)
    const clearValidationErrors = useCallback(() => {
        setLocalErrors({});
    }, []);

    // Provide getFormData, validateForm, updateSchema, schemaId, formController, and formMethod to all child components
    const schemaContext = useMemo<SchemaContextValue>(
        () => ({
            getFormData,
            validateForm,
            updateSchema,
            schemaId: schemaId || null,
            formController,
            formMethod,
        }),
        [getFormData, validateForm, updateSchema, schemaId, formController, formMethod],
    );

    // Expose getFormData, validateForm, and clearValidationErrors to parent components via ref
    useImperativeHandle(ref, () => ({ getFormData, validateForm, clearValidationErrors }), [
        getFormData,
        validateForm,
        clearValidationErrors,
    ]);

    // Check if the next item is an action
    const isNextItemAction = (index: number) => {
        const nextItem = internalSchema[index + 1];
        return nextItem && isAction(nextItem);
    };

    // Check if the previous item is an action
    const isPreviousItemAction = (index: number) => {
        const prevItem = internalSchema[index - 1];
        return prevItem && isAction(prevItem);
    };

    // Get all consecutive actions starting from the next index
    const getConsecutiveActions = (startIndex: number) => {
        const actions = [];
        let currentIndex = startIndex + 1;

        while (currentIndex < internalSchema.length && isAction(internalSchema[currentIndex])) {
            actions.push(internalSchema[currentIndex]);
            currentIndex++;
        }

        return actions;
    };

    // Determine container spacing based on what we're rendering
    const containerClass = (() => {
        if (!internalSchema || !Array.isArray(internalSchema) || internalSchema.length === 0) return '';

        // Check if we're rendering sections - if so, use space-y-12
        const hasSections = internalSchema.some((c) => c.component === 'section');
        if (hasSections) return 'space-y-12';

        // Otherwise use space-y-6 for general spacing
        return 'space-y-6';
    })();

    // Get error message for a component
    const getError = (component: any) => {
        if (!component.name || !errors) return undefined;
        const error = (errors as Record<string, string | string[]>)[component.name];
        return Array.isArray(error) ? error[0] : error;
    };

    const Container = as === 'div' ? 'div' : 'form';

    // Wrapper for form actions that can collect form data
    const renderAction = (action: any, key: string | number) => (
        <ActionButton key={key} {...({ ...action, getFormData } as any)} />
    );

    return (
        <SchemaContext.Provider value={schemaContext}>
            {/* Override the errors provided by ErrorProvider with our merged errors (local + server) */}
            <ErrorsContext.Provider value={errors}>
                <Container
                    ref={setFormElement}
                    className={containerClass}
                    onSubmit={(e: FormEvent<HTMLElement>) => e.preventDefault()}
                >
                    {(Array.isArray(internalSchema) ? internalSchema : []).map((component: any, index: number) => {
                        const key = component.name || component.id || index;

                        // Group consecutive actions together (only render on first action in group)
                        if (isAction(component) && !isPreviousItemAction(index) && isNextItemAction(index)) {
                            return (
                                <div key={key} className="flex flex-wrap gap-2 items-start">
                                    {renderAction(component, 'first')}
                                    {getConsecutiveActions(index).map((nextComponent: any, nextIndex: number) =>
                                        renderAction(nextComponent, nextComponent.name || nextComponent.id || index + nextIndex + 1),
                                    )}
                                </div>
                            );
                        }

                        // Render single action (not part of a group)
                        if (isAction(component) && !isPreviousItemAction(index) && !isNextItemAction(index)) {
                            return renderAction(component, key);
                        }

                        // Render regular form components
                        if (!isAction(component)) {
                            const Component = resolveComponent(toLaraviltName(component.component));

                            if (!Component) {
                                return <div key={key} />;
                            }

                            return (
                                <Component
                                    key={key}
                                    {...getComponentProps(component)}
                                    value={isSchemaComponent(component) ? undefined : internalFormData[component.name]}
                                    modelValue={isSchemaComponent(component) ? internalFormData : internalFormData[component.name]}
                                    disabled={disabled || component.disabled}
                                    error={getError(component)}
                                    onUpdateModelValue={(value: any) => handleComponentUpdate(component, value)}
                                />
                            );
                        }

                        return <Fragment key={key} />;
                    })}
                </Container>
            </ErrorsContext.Provider>
        </SchemaContext.Provider>
    );
}
