// resources/js/components/MarkdownEditor.vue
<template>
  <div class="laravilt-markdown-editor">
    <!-- Toolbar -->
    <div class="border border-gray-300 border-b-0 rounded-t-lg bg-gray-50 px-3 py-2 dark:border-gray-600 dark:bg-gray-700">
      <div class="flex flex-wrap gap-1">
        <button
          v-for="button in toolbarButtons"
          :key="button.name"
          type="button"
          @click="executeCommand(button.command, button.value)"
          :title="button.title"
          :disabled="disabled"
          class="p-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 rounded disabled:opacity-50 disabled:cursor-not-allowed dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"
        >
          <component :is="button.icon" class="h-4 w-4" />
        </button>

        <div class="border-l border-gray-300 dark:border-gray-600 mx-1"></div>

        <!-- View Mode Toggle -->
        <button
          type="button"
          @click="viewMode = 'editor'"
          :class="{ 'bg-gray-200 dark:bg-gray-600': viewMode === 'editor' }"
          class="px-3 py-2 text-xs font-medium text-gray-600 hover:bg-gray-200 rounded dark:text-gray-400 dark:hover:bg-gray-600"
        >
          Editor
        </button>
        <button
          type="button"
          @click="viewMode = 'preview'"
          :class="{ 'bg-gray-200 dark:bg-gray-600': viewMode === 'preview' }"
          class="px-3 py-2 text-xs font-medium text-gray-600 hover:bg-gray-200 rounded dark:text-gray-400 dark:hover:bg-gray-600"
        >
          Preview
        </button>
        <button
          type="button"
          @click="viewMode = 'split'"
          :class="{ 'bg-gray-200 dark:bg-gray-600': viewMode === 'split' }"
          class="px-3 py-2 text-xs font-medium text-gray-600 hover:bg-gray-200 rounded dark:text-gray-400 dark:hover:bg-gray-600"
        >
          Split
        </button>
      </div>
    </div>

    <!-- Editor and Preview Area -->
    <div class="border border-gray-300 rounded-b-lg dark:border-gray-600">
      <div :class="viewModeClass">
        <!-- Editor -->
        <div v-show="viewMode === 'editor' || viewMode === 'split'" class="relative">
          <textarea
            ref="textarea"
            :value="modelValue"
            @input="updateValue"
            :placeholder="placeholder"
            :required="required"
            :disabled="disabled"
            :rows="rows"
            class="block w-full border-0 focus:ring-0 font-mono text-sm dark:bg-gray-800 dark:text-white"
            :style="{ minHeight: minHeight + 'px', maxHeight: maxHeight ? maxHeight + 'px' : 'none' }"
          ></textarea>
        </div>

        <!-- Preview -->
        <div
          v-show="viewMode === 'preview' || viewMode === 'split'"
          class="prose prose-sm max-w-none p-4 overflow-auto dark:prose-invert"
          :style="{ minHeight: minHeight + 'px', maxHeight: maxHeight ? maxHeight + 'px' : 'none' }"
          v-html="renderedMarkdown"
        ></div>
      </div>
    </div>

    <!-- Footer: Character/Word Count -->
    <div v-if="showCharacterCount || showWordCount" class="mt-1.5 flex justify-end gap-4 text-xs text-gray-500">
      <span v-if="showCharacterCount">
        {{ characterCount }}
        <template v-if="maxLength"> / {{ maxLength }}</template>
        characters
      </span>
      <span v-if="showWordCount">
        {{ wordCount }} words
      </span>
    </div>

    <!-- Hidden Input -->
    <input type="hidden" :name="name" :value="modelValue" />
  </div>
</template>

<script>
export default {
  name: 'LaraviltMarkdownEditor',

  props: {
    modelValue: {
      type: String,
      default: ''
    },
    name: {
      type: String,
      required: true
    },
    placeholder: String,
    required: Boolean,
    disabled: Boolean,
    rows: {
      type: Number,
      default: 10
    },
    minHeight: {
      type: Number,
      default: 200
    },
    maxHeight: Number,
    maxLength: Number,
    showCharacterCount: Boolean,
    showWordCount: Boolean,
    toolbarButtons: {
      type: Array,
      default: () => [
        { name: 'bold', command: 'bold', title: 'Bold (Ctrl+B)', icon: 'BoldIcon' },
        { name: 'italic', command: 'italic', title: 'Italic (Ctrl+I)', icon: 'ItalicIcon' },
        { name: 'heading', command: 'heading', value: 1, title: 'Heading', icon: 'HeadingIcon' },
        { name: 'quote', command: 'quote', title: 'Quote', icon: 'QuoteIcon' },
        { name: 'code', command: 'code', title: 'Code', icon: 'CodeIcon' },
        { name: 'link', command: 'link', title: 'Link (Ctrl+K)', icon: 'LinkIcon' },
        { name: 'image', command: 'image', title: 'Image', icon: 'ImageIcon' },
        { name: 'list', command: 'list', value: 'ul', title: 'Bullet List', icon: 'ListIcon' },
        { name: 'orderedList', command: 'list', value: 'ol', title: 'Numbered List', icon: 'OrderedListIcon' },
        { name: 'table', command: 'table', title: 'Table', icon: 'TableIcon' }
      ]
    }
  },

  emits: ['update:modelValue'],

  data() {
    return {
      viewMode: 'split' // 'editor', 'preview', 'split'
    };
  },

  computed: {
    characterCount() {
      return this.modelValue.length;
    },

    wordCount() {
      return this.modelValue.trim().split(/\s+/).filter(w => w.length > 0).length;
    },

    viewModeClass() {
      if (this.viewMode === 'split') {
        return 'grid grid-cols-2 divide-x divide-gray-300 dark:divide-gray-600';
      }
      return '';
    },

    renderedMarkdown() {
      // Simple markdown to HTML conversion
      // In production, use a library like marked.js or markdown-it
      let html = this.modelValue;

      // Headings
      html = html.replace(/^### (.*$)/gim, '<h3>$1</h3>');
      html = html.replace(/^## (.*$)/gim, '<h2>$1</h2>');
      html = html.replace(/^# (.*$)/gim, '<h1>$1</h1>');

      // Bold
      html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');

      // Italic
      html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

      // Links
      html = html.replace(/\[(.*?)\]\((.*?)\)/g, '<a href="$2">$1</a>');

      // Images
      html = html.replace(/!\[(.*?)\]\((.*?)\)/g, '<img src="$2" alt="$1" />');

      // Code blocks
      html = html.replace(/```([\s\S]*?)```/g, '<pre><code>$1</code></pre>');

      // Inline code
      html = html.replace(/`(.*?)`/g, '<code>$1</code>');

      // Blockquotes
      html = html.replace(/^> (.*$)/gim, '<blockquote>$1</blockquote>');

      // Unordered lists
      html = html.replace(/^\* (.*$)/gim, '<li>$1</li>');
      html = html.replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>');

      // Ordered lists
      html = html.replace(/^\d+\. (.*$)/gim, '<li>$1</li>');

      // Line breaks
      html = html.replace(/\n/g, '<br>');

      return html;
    }
  },

  methods: {
    updateValue(event) {
      this.$emit('update:modelValue', event.target.value);
    },

    executeCommand(command, value = null) {
      const textarea = this.$refs.textarea;
      const start = textarea.selectionStart;
      const end = textarea.selectionEnd;
      const selectedText = this.modelValue.substring(start, end);
      let replacement = '';

      switch (command) {
        case 'bold':
          replacement = `**${selectedText || 'bold text'}**`;
          break;

        case 'italic':
          replacement = `*${selectedText || 'italic text'}*`;
          break;

        case 'heading':
          const level = value || 1;
          const prefix = '#'.repeat(level);
          replacement = `${prefix} ${selectedText || 'Heading'}`;
          break;

        case 'quote':
          replacement = `> ${selectedText || 'Quote'}`;
          break;

        case 'code':
          if (selectedText.includes('\n')) {
            replacement = `\`\`\`\n${selectedText || 'code'}\n\`\`\``;
          } else {
            replacement = `\`${selectedText || 'code'}\``;
          }
          break;

        case 'link':
          replacement = `[${selectedText || 'link text'}](url)`;
          break;

        case 'image':
          replacement = `![${selectedText || 'alt text'}](image-url)`;
          break;

        case 'list':
          if (value === 'ul') {
            const lines = selectedText.split('\n');
            replacement = lines.map(line => `* ${line}`).join('\n');
          } else if (value === 'ol') {
            const lines = selectedText.split('\n');
            replacement = lines.map((line, i) => `${i + 1}. ${line}`).join('\n');
          }
          break;

        case 'table':
          replacement = `| Header 1 | Header 2 |\n| -------- | -------- |\n| Cell 1   | Cell 2   |`;
          break;

        default:
          return;
      }

      const newValue =
        this.modelValue.substring(0, start) +
        replacement +
        this.modelValue.substring(end);

      this.$emit('update:modelValue', newValue);

      // Restore focus and selection
      this.$nextTick(() => {
        textarea.focus();
        textarea.setSelectionRange(
          start + replacement.length,
          start + replacement.length
        );
      });
    }
  },

  mounted() {
    // Add keyboard shortcuts
    this.$refs.textarea.addEventListener('keydown', (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'b') {
        e.preventDefault();
        this.executeCommand('bold');
      } else if ((e.ctrlKey || e.metaKey) && e.key === 'i') {
        e.preventDefault();
        this.executeCommand('italic');
      } else if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
        e.preventDefault();
        this.executeCommand('link');
      }
    });
  }
};
</script>

<style scoped>
.laravilt-markdown-editor textarea {
  resize: vertical;
}

.prose {
  color: inherit;
}

.prose h1,
.prose h2,
.prose h3 {
  margin-top: 1em;
  margin-bottom: 0.5em;
}

.prose code {
  background-color: rgba(0, 0, 0, 0.05);
  padding: 0.2em 0.4em;
  border-radius: 3px;
  font-size: 0.9em;
}

.prose pre {
  background-color: rgba(0, 0, 0, 0.05);
  padding: 1em;
  border-radius: 5px;
  overflow-x: auto;
}

.prose blockquote {
  border-left: 4px solid #ddd;
  padding-left: 1em;
  color: #666;
  font-style: italic;
}

.prose ul,
.prose ol {
  padding-left: 2em;
}

.prose table {
  width: 100%;
  border-collapse: collapse;
}

.prose th,
.prose td {
  border: 1px solid #ddd;
  padding: 0.5em;
  text-align: left;
}

.prose th {
  background-color: rgba(0, 0, 0, 0.05);
  font-weight: bold;
}
</style>

// resources/react/components/fields/MarkdownEditor.tsx
import {
    Bold,
    Code,
    Eye,
    EyeOff,
    Heading2,
    Image,
    Italic,
    Link,
    List,
    ListOrdered,
    Quote,
    Redo,
    Strikethrough,
    Table,
    Undo,
    type LucideIcon,
} from 'lucide-react';
import MarkdownIt from 'markdown-it';
import { Fragment, useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react';

import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { resolveIcon } from '@laravilt/support/lib/icons';

// Scoped <style> block of MarkdownEditor.vue (`.markdown-preview :deep(x)` -> `.markdown-preview x`)
const MARKDOWN_EDITOR_STYLES = `
.markdown-preview {
  color: var(--foreground);
  font-size: 0.875rem;
  line-height: 1.625;
}

.markdown-preview h1 {
  font-size: 1.875rem;
  font-weight: 700;
  margin-top: 0;
  margin-bottom: 1rem;
  line-height: 2.25rem;
  color: var(--foreground);
}

.markdown-preview h2 {
  font-size: 1.5rem;
  font-weight: 600;
  margin-top: 1.5rem;
  margin-bottom: 0.75rem;
  line-height: 2rem;
  color: var(--foreground);
}

.markdown-preview h3 {
  font-size: 1.25rem;
  font-weight: 600;
  margin-top: 1.25rem;
  margin-bottom: 0.5rem;
  line-height: 1.75rem;
  color: var(--foreground);
}

.markdown-preview h4 {
  font-size: 1.125rem;
  font-weight: 600;
  margin-top: 1rem;
  margin-bottom: 0.5rem;
  line-height: 1.5rem;
  color: var(--foreground);
}

.markdown-preview h5,
.markdown-preview h6 {
  font-size: 1rem;
  font-weight: 600;
  margin-top: 1rem;
  margin-bottom: 0.5rem;
  line-height: 1.5rem;
  color: var(--foreground);
}

.markdown-preview p {
  margin-top: 0;
  margin-bottom: 1rem;
}

.markdown-preview a {
  color: var(--primary);
  text-decoration: underline;
  text-underline-offset: 2px;
}

.markdown-preview a:hover {
  opacity: 0.8;
}

.markdown-preview strong {
  font-weight: 600;
  color: var(--foreground);
}

.markdown-preview em {
  font-style: italic;
}

.markdown-preview code {
  background-color: var(--muted);
  padding: 0.125rem 0.375rem;
  border-radius: 0.25rem;
  font-size: 0.875em;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  color: var(--foreground);
}

.markdown-preview pre {
  background-color: var(--muted);
  padding: 1rem;
  border-radius: 0.5rem;
  overflow-x: auto;
  margin-top: 0;
  margin-bottom: 1rem;
}

.markdown-preview pre code {
  background-color: transparent;
  padding: 0;
  border-radius: 0;
  font-size: 0.875rem;
}

.markdown-preview ul,
.markdown-preview ol {
  margin-top: 0;
  margin-bottom: 1rem;
  padding-left: 1.625rem;
}

.markdown-preview ul {
  list-style-type: disc;
}

.markdown-preview ol {
  list-style-type: decimal;
}

.markdown-preview li {
  margin-top: 0.25rem;
  margin-bottom: 0.25rem;
}

.markdown-preview blockquote {
  border-left: 4px solid var(--border);
  padding-left: 1rem;
  margin: 1rem 0;
  font-style: italic;
  color: var(--muted-foreground);
}

.markdown-preview hr {
  border: none;
  border-top: 1px solid var(--border);
  margin: 1.5rem 0;
}

.markdown-preview table {
  width: 100%;
  border-collapse: collapse;
  margin: 1rem 0;
}

.markdown-preview th,
.markdown-preview td {
  border: 1px solid var(--border);
  padding: 0.5rem 0.75rem;
  text-align: left;
}

.markdown-preview th {
  background-color: var(--muted);
  font-weight: 600;
}

.markdown-preview img {
  max-width: 100%;
  height: auto;
  border-radius: 0.5rem;
  margin: 1rem 0;
}
`;

export interface MarkdownEditorProps {
    name?: string;
    value?: string;
    modelValue?: string;
    label?: string;
    placeholder?: string;
    preview?: boolean;
    disabled?: boolean;
    required?: boolean;
    helperText?: string;
    prefixIcon?: string;
    suffixIcon?: string;
    prefixIconColor?: string;
    suffixIconColor?: string;
    toolbarButtons?: string[][];
    fileAttachmentsEnabled?: boolean;
    fileAttachmentsDisk?: string;
    fileAttachmentsDirectory?: string;
    fileAttachmentsAcceptedFileTypes?: string[];
    fileAttachmentsMaxSize?: number;
    onUpdateModelValue?: (value: string) => void;
    onUpdateValue?: (value: string) => void;
    [key: string]: any;
}

const DEFAULT_TOOLBAR_BUTTONS: string[][] = [
    ['bold', 'italic', 'strike', 'link'],
    ['heading'],
    ['blockquote', 'codeBlock', 'bulletList', 'orderedList'],
    ['table', 'attachFiles'],
    ['undo', 'redo'],
];

const DEFAULT_ACCEPTED_FILE_TYPES: string[] = ['image/png', 'image/jpeg', 'image/gif', 'image/webp'];

// Toolbar button icons mapping
const toolbarIcons: Record<string, LucideIcon> = {
    bold: Bold,
    italic: Italic,
    strike: Strikethrough,
    link: Link,
    heading: Heading2,
    blockquote: Quote,
    codeBlock: Code,
    bulletList: List,
    orderedList: ListOrdered,
    table: Table,
    attachFiles: Image,
    undo: Undo,
    redo: Redo,
};

// Helper to get Tailwind color classes for icons
const getIconColorClass = (color?: string): string => {
    if (!color) return 'text-muted-foreground';

    const colorMap: Record<string, string> = {
        primary: 'text-primary',
        secondary: 'text-secondary',
        success: 'text-green-600',
        danger: 'text-red-600',
        warning: 'text-yellow-600',
        info: 'text-blue-600',
        muted: 'text-muted-foreground',
        destructive: 'text-destructive',
    };

    return colorMap[color] || `text-${color}`;
};

export default function MarkdownEditor({
    name,
    value,
    modelValue = '',
    label,
    placeholder = 'Write markdown...',
    preview = true,
    disabled = false,
    required,
    helperText,
    prefixIcon,
    suffixIcon,
    prefixIconColor,
    suffixIconColor,
    toolbarButtons = DEFAULT_TOOLBAR_BUTTONS,
    fileAttachmentsEnabled = false,
    fileAttachmentsAcceptedFileTypes = DEFAULT_ACCEPTED_FILE_TYPES,
    fileAttachmentsMaxSize = 12288, // 12 MB
    onUpdateModelValue,
    onUpdateValue,
}: MarkdownEditorProps) {
    const externalValue = value ?? modelValue;

    // Internal state for markdown content (a ref mirror keeps async callbacks on the latest value)
    const [internalValue, setInternalValueState] = useState<string>(() => externalValue ?? '');
    const internalValueRef = useRef<string>(internalValue);
    const setInternalValue = (next: string) => {
        internalValueRef.current = next;
        setInternalValueState(next);
    };

    // Watch for prop changes and update internal state
    useEffect(() => {
        setInternalValue(externalValue ?? '');
    }, [externalValue]);

    const [showPreview, setShowPreview] = useState<boolean>(preview);
    const textareaRef = useRef<HTMLTextAreaElement>(null);
    const fileInputRef = useRef<HTMLInputElement>(null);
    const uploadHistory = useRef<Array<{ action: string; value: string }>>([]);
    const uploadHistoryIndex = useRef(-1);

    // Initialize markdown-it with sensible defaults
    const md = useMemo(
        () =>
            new MarkdownIt({
                html: false, // Disable HTML tags in source for security
                xhtmlOut: false,
                breaks: true, // Convert \n to <br>
                linkify: true, // Auto-convert URL-like text to links
                typographer: true, // Enable smart quotes and other typographic replacements
            }),
        [],
    );

    // Rendered HTML
    const renderedHtml = useMemo(() => {
        if (!internalValue) return '';
        return md.render(internalValue);
    }, [md, internalValue]);

    const emitValue = (newValue: string) => {
        onUpdateModelValue?.(newValue);
        onUpdateValue?.(newValue);
    };

    // Save action to history
    const saveToHistory = (action: string, historyValue: string) => {
        uploadHistory.current = uploadHistory.current.slice(0, uploadHistoryIndex.current + 1);
        uploadHistory.current.push({ action, value: historyValue });
        uploadHistoryIndex.current = uploadHistory.current.length - 1;
    };

    // Insert markdown syntax at cursor position
    const insertMarkdown = (before: string, after: string = '', insertPlaceholder: string = '') => {
        const textarea = textareaRef.current;
        if (!textarea) return;

        const current = internalValueRef.current;
        const start = textarea.selectionStart;
        const end = textarea.selectionEnd;
        const selectedText = current.substring(start, end);
        const replacement = before + (selectedText || insertPlaceholder) + after;

        const newValue = current.substring(0, start) + replacement + current.substring(end);

        // Save to history for undo/redo
        saveToHistory('insert', newValue);

        // Update internal state
        setInternalValue(newValue);

        // Emit events
        emitValue(newValue);

        // Set cursor position after insertion
        setTimeout(() => {
            if (selectedText) {
                textarea.setSelectionRange(start + before.length, start + before.length + selectedText.length);
            } else {
                textarea.setSelectionRange(start + before.length, start + before.length + insertPlaceholder.length);
            }
            textarea.focus();
        }, 0);
    };

    // Undo last action
    const undo = () => {
        if (uploadHistoryIndex.current > 0) {
            uploadHistoryIndex.current--;
            const newValue = uploadHistory.current[uploadHistoryIndex.current].value;
            setInternalValue(newValue);
            emitValue(newValue);
        }
    };

    // Redo last undone action
    const redo = () => {
        if (uploadHistoryIndex.current < uploadHistory.current.length - 1) {
            uploadHistoryIndex.current++;
            const newValue = uploadHistory.current[uploadHistoryIndex.current].value;
            setInternalValue(newValue);
            emitValue(newValue);
        }
    };

    // Handle toolbar button clicks
    const handleToolbarAction = (action: string) => {
        switch (action) {
            case 'bold':
                insertMarkdown('**', '**', 'bold text');
                break;
            case 'italic':
                insertMarkdown('*', '*', 'italic text');
                break;
            case 'strike':
                insertMarkdown('~~', '~~', 'strikethrough text');
                break;
            case 'link':
                insertMarkdown('[', '](url)', 'link text');
                break;
            case 'heading':
                insertMarkdown('## ', '', 'Heading');
                break;
            case 'blockquote':
                insertMarkdown('> ', '', 'Quote');
                break;
            case 'codeBlock':
                insertMarkdown('```\n', '\n```', 'code');
                break;
            case 'bulletList':
                insertMarkdown('- ', '', 'List item');
                break;
            case 'orderedList':
                insertMarkdown('1. ', '', 'List item');
                break;
            case 'table':
                insertMarkdown('| Column 1 | Column 2 |\n|----------|----------|\n| ', ' | Cell 2 |', 'Cell 1');
                break;
            case 'attachFiles':
                fileInputRef.current?.click();
                break;
            case 'undo':
                undo();
                break;
            case 'redo':
                redo();
                break;
        }
    };

    // Handle file upload
    const handleFileUpload = async (event: ChangeEvent<HTMLInputElement>) => {
        const target = event.target;
        const file = target.files?.[0];

        if (!file) return;

        // Validate file type
        if (!fileAttachmentsAcceptedFileTypes.includes(file.type)) {
            alert(`File type not accepted. Allowed types: ${fileAttachmentsAcceptedFileTypes.join(', ')}`);
            return;
        }

        // Validate file size (convert to KB)
        const fileSizeKB = file.size / 1024;
        if (fileSizeKB > fileAttachmentsMaxSize) {
            alert(`File size exceeds maximum allowed size of ${fileAttachmentsMaxSize} KB`);
            return;
        }

        // TODO: Implement actual file upload to Laravel backend
        // For now, we'll create a data URL for preview
        const reader = new FileReader();
        reader.onload = (e) => {
            const imageUrl = e.target?.result as string;
            insertMarkdown('![', `](${imageUrl})`, file.name);
        };
        reader.readAsDataURL(file);

        // Reset file input
        target.value = '';
    };

    const handleInput = (event: ChangeEvent<HTMLTextAreaElement>) => {
        const newValue = event.target.value;
        setInternalValue(newValue);
        emitValue(newValue);
    };

    const togglePreview = () => {
        setShowPreview((previous) => !previous);
    };

    const PrefixIcon = resolveIcon(prefixIcon);
    const SuffixIcon = resolveIcon(suffixIcon);
    const PreviewIcon = showPreview ? EyeOff : Eye;

    return (
        <div className="w-full space-y-2">
            <style href="laravilt-forms-markdown-editor" precedence="default">
                {MARKDOWN_EDITOR_STYLES}
            </style>

            {/* Label */}
            {label && (
                <label htmlFor={name} className="text-sm font-medium block text-foreground">
                    {label}{' '}
                    {required && <span className="text-destructive ms-0.5">*</span>}
                </label>
            )}

            {/* Hidden input for form submission */}
            {name && <input type="hidden" name={name} value={internalValue} />}

            {/* Header with icons and preview toggle */}
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                    {PrefixIcon && <PrefixIcon className={cn('h-4 w-4', getIconColorClass(prefixIconColor))} />}
                </div>
                <div className="flex items-center gap-2">
                    <Button type="button" variant="ghost" size="sm" onClick={togglePreview}>
                        <PreviewIcon className="h-4 w-4 mr-2" />
                        {showPreview ? 'Hide' : 'Show'} Preview
                    </Button>
                    {SuffixIcon && <SuffixIcon className={cn('h-4 w-4', getIconColorClass(suffixIconColor))} />}
                </div>
            </div>

            {/* Toolbar */}
            {toolbarButtons && toolbarButtons.length > 0 && (
                <div className="flex flex-wrap items-center gap-1 p-2 border border-input rounded-md bg-muted/50">
                    {toolbarButtons.map((group, groupIndex) => (
                        <Fragment key={groupIndex}>
                            <div className="flex items-center gap-1">
                                {group.map((button) => {
                                    const ToolbarIcon = toolbarIcons[button];

                                    return (
                                        <Button
                                            key={button}
                                            type="button"
                                            variant="ghost"
                                            size="sm"
                                            className="h-8 w-8 p-0"
                                            disabled={disabled || (button === 'attachFiles' && !fileAttachmentsEnabled)}
                                            title={button}
                                            onClick={() => handleToolbarAction(button)}
                                        >
                                            {ToolbarIcon && <ToolbarIcon className="h-4 w-4" />}
                                        </Button>
                                    );
                                })}
                            </div>
                            {groupIndex < toolbarButtons.length - 1 && <div className="h-6 w-px bg-border" />}
                        </Fragment>
                    ))}
                </div>
            )}

            {/* Hidden file input for image uploads */}
            {fileAttachmentsEnabled && (
                <input
                    ref={fileInputRef}
                    type="file"
                    accept={fileAttachmentsAcceptedFileTypes.join(',')}
                    className="hidden"
                    onChange={handleFileUpload}
                />
            )}

            {/* Editor container */}
            <div className={cn('grid gap-4', showPreview ? 'md:grid-cols-2' : 'grid-cols-1')}>
                {/* Editor */}
                <div>
                    <textarea
                        ref={textareaRef}
                        value={internalValue}
                        placeholder={placeholder}
                        disabled={disabled}
                        rows={12}
                        className="flex min-h-[240px] w-full rounded-md border border-input bg-background px-3 py-2 text-base ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm font-mono"
                        onChange={handleInput}
                    />
                </div>

                {/* Preview */}
                {showPreview && (
                    <div className="border border-input rounded-md p-4 bg-background min-h-[200px] overflow-auto">
                        {renderedHtml ? (
                            <div className="markdown-preview" dangerouslySetInnerHTML={{ __html: renderedHtml }} />
                        ) : (
                            <p className="text-muted-foreground text-sm">Start typing to see a preview...</p>
                        )}
                    </div>
                )}
            </div>

            {/* Helper text */}
            {helperText && <p className="text-xs text-muted-foreground mt-1">{helperText}</p>}
        </div>
    );
}
